stages:
- buildTwilio
- buildShawnsApp
- testTwilio
- testShawnsApp

buildTwilio:
  stage: buildTwilio
  script:
    - cd SMS_API/twilio
    - ./gradlew assemble

BuildShawnsApp:
  stage: buildShawnsApp
  script:
    - cd ShawnsApp
    - echo build

BuildShawnsApp:
  stage: testTwilio
  script:
    - cd cd SMS_API/twilio
    - echo test Twilio

BuildShawnsApp:
  stage: testShawnsApp
  script:
    - cd ShawnsApp
    - echo test ShawnsApp








